package com.example.taxiradar

import android.content.Context

/** The short status answers “is it working”; this answers “why and how”. */
object PermissionExplanations {
    fun forTitle(c: Context, title: String): String {
        fun t(ru: String, ro: String) = DriverUi.t(c, ru, ro)
        return when (title) {
            c.getString(R.string.chk_acc) -> t(
                "Служба специальных возможностей читает текст карточки заказа в Яндекс Про: адреса, километры, минуты и заезды. По этим данным радар рассчитывает ориентировочную цену и точку Б. Без службы приложение не узнает, какой заказ вы видите. Оно не принимает и не отклоняет заказ вместо вас. Разрешение Android относится к чтению экрана, поэтому включайте именно Taxi Radar. После обновления система иногда оставляет переключатель включённым, но отключает службу: выключите и включите её снова. Зелёная проверка означает, что служба действительно подключилась.",
                "Serviciul de accesibilitate citește textul ofertei Yandex Pro: adrese, km, minute și opriri. Radarul estimează prețul și destinația B din aceste date. Fără serviciu nu știe ce ofertă vedeți. Nu acceptă și nu refuză curse în locul dvs. Permisiunea permite citirea ecranului; activați exact Taxi Radar. După actualizare comutatorul poate rămâne activ fără serviciul conectat: opriți și reporniți-l. Verificarea verde confirmă conectarea reală.")
            c.getString(R.string.chk_overlay) -> t(
                "Позволяет показывать плавающее окно с ценой поверх Яндекс Про и навигатора, чтобы не переключать приложения на каждом заказе. Это отдельное разрешение: оно не читает карточки и не заменяет специальные возможности. Без него расчёт не будет виден поверх другого приложения. Виджет можно перемещать и скрывать. Если Android не даёт включить другое разрешение из-за окна поверх экрана, сначала остановите виджет, выдайте разрешение и запустите его снова.",
                "Permite afișarea ferestrei cu preț peste Yandex Pro și navigator, fără schimbarea aplicației la fiecare ofertă. Nu citește ofertele și nu înlocuiește accesibilitatea. Fără ea estimarea nu apare peste alte aplicații. Widgetul poate fi mutat sau ascuns. Dacă Android blochează o altă permisiune din cauza suprapunerii, opriți widgetul, acordați permisiunea și reporniți-l.")
            c.getString(R.string.chk_battery), c.getString(R.string.chk_activity) -> t(
                "Android экономит заряд, останавливая приложения в фоне. На смене это может убрать виджет, прекратить обновление надбавки или задержать дорожные предупреждения, хотя Яндекс Про продолжает работать. Режим «Без ограничений» разрешает службе радара оставаться активной. Он не включает радар самостоятельно и не обещает нулевой расход батареи: геолокация и запросы используют энергию. После смены остановите радар. На Xiaomi дополнительно проверьте контроль активности и фоновый автозапуск; на Samsung — список спящих приложений.",
                "Android economisește bateria oprind aplicațiile din fundal. În tură aceasta poate ascunde widgetul, opri suplimentul sau întârzia avertizările, deși Yandex Pro funcționează. «Fără restricții» permite serviciului radarului să rămână activ. Nu pornește singur radarul și nu elimină consumul: GPS și cererile folosesc energie. Opriți radarul după tură. Pe Xiaomi verificați și pornirea în fundal; pe Samsung lista aplicațiilor în repaus.")
            c.getString(R.string.chk_location) -> t(
                "Надбавка зависит от точки на карте: даже соседняя улица может иметь другой спрос. Геолокация нужна для надбавки рядом с вами, отметки «я здесь», предупреждений о дорожных метках и очереди аэропорта. Точная геолокация лучше приблизительной. Без актуальной позиции виджет показывает значок точки, а не выдаёт надбавку другого района за вашу. Чтение карточки и расчёт поездки могут работать отдельно. Доступ запрашивается для функций радара; разрешение не заменяет включённый GPS и наличие сигнала.",
                "Suplimentul depinde de poziție: o stradă vecină poate avea altă cerere. Localizarea este necesară pentru suplimentul din apropiere, poziția pe hartă, avertizările rutiere și coada aeroportului. Poziția precisă este mai utilă decât cea aproximativă. Fără poziție actuală widgetul afișează un simbol, nu suplimentul altei zone. Citirea ofertei și estimarea pot funcționa separat. Permisiunea nu înlocuiește GPS activ și semnalul disponibil.")
            c.getString(R.string.chk_notif) -> t(
                "Уведомления показывают работу службы, предупреждают о метках впереди и дают кнопки «Ещё здесь / Уже нет». Дополнительные сообщения о надбавке и прилётах появляются только при включённых настройках помощника. Если запретить уведомления или отдельный канал, вы можете пропустить предупреждение, хотя виджет работает. Проверьте также звук и режим «Не беспокоить». Само разрешение не запускает слежение за дорогой: для него отдельно включите предупреждения на карте.",
                "Notificările arată serviciul activ, avertizează despre marcaje și oferă butoane «Încă aici / Nu mai este». Suplimentul și aterizările se anunță doar dacă activați opțiunile asistentului. Dacă opriți notificările sau un canal, puteți rata avertizări deși widgetul funcționează. Verificați sunetul și «Nu deranjați». Permisiunea nu activează singură avertizările rutiere: porniți-le separat pe hartă.")
            c.getString(R.string.chk_restricted) -> t(
                "Для APK, установленного из файла, Android может блокировать включение специальных возможностей. Разрешение ограниченных настроек снимает именно эту блокировку для Taxi Radar; оно не включает службу автоматически. Откройте страницу приложения, разрешите ограниченные настройки, затем вернитесь в специальные возможности. Пункт зависит от производителя и способа установки. Если его нет, раскройте инструкцию Samsung или Xiaomi; не выдавайте доступ сторонним приложениям ради этого шага.",
                "Pentru un APK instalat din fișier Android poate bloca accesibilitatea. Permiterea setărilor restricționate elimină această blocare pentru Taxi Radar; nu activează automat serviciul. Permiteți-le din pagina aplicației, apoi reveniți la accesibilitate. Opțiunea depinde de producător și instalare. Dacă lipsește, deschideți ghidul Samsung sau Xiaomi; nu acordați acces altor aplicații pentru acest pas.")
            c.getString(R.string.chk_autostart), c.getString(R.string.chk_lock) -> t(
                "На некоторых прошивках приложение может быть остановлено при очистке недавних программ или после перезапуска телефона. Фоновый автозапуск и замок в недавних уменьшают риск такого отключения. Это настройки производителя, и Android не всегда позволяет радару проверить их автоматически: знак вопроса означает ручную проверку, а не ошибку. Они не заменяют запуск виджета и разрешения чтения карточек. Если замка или автозапуска нет на вашем телефоне, используйте доступные настройки батареи.",
                "Unele sisteme opresc aplicația la curățarea aplicațiilor recente sau după repornire. Pornirea în fundal și lacătul din recente reduc acest risc. Radarul nu le poate verifica automat pe toate telefoanele: semnul întrebării înseamnă verificare manuală, nu eroare. Nu înlocuiesc pornirea widgetului și accesibilitatea. Dacă opțiunile lipsesc, folosiți setările bateriei disponibile.")
            c.getString(R.string.chk_key) -> t(
                "Ключ даёт доступ к геокодированию: превращению адресов в координаты для расчёта маршрута. Если используется общий геокодер сервера, собственный ключ не обязателен. Проверка отличает отсутствие ключа, отказ сервиса и проблему сети. Даже правильный ключ не гарантирует, что неоднозначный адрес будет найден: уточните улицу и дом. Здесь проверяется доступ к сервису, а не лицензия Taxi Radar.",
                "Cheia permite geocodarea: transformarea adreselor în coordonate pentru traseu. Cu geocodorul comun al serverului cheia proprie nu este obligatorie. Verificarea separă lipsa cheii, refuzul serviciului și problema de rețea. O cheie corectă nu garantează găsirea unei adrese ambigue. Se verifică serviciul de adrese, nu licența Taxi Radar.")
            c.getString(R.string.chk_license) -> t(
                "Лицензия определяет доступ к функциям Taxi Radar и общим данным водителей. Она не выдаёт системные разрешения: даже при активной подписке отдельно нужны чтение карточек и окно поверх приложений. Если подписка не активна, откройте профиль и проверьте устройство, срок и активацию. Для синхронизации статуса нужна связь с сервером.",
                "Licența controlează accesul la funcțiile Taxi Radar și datele comunității. Nu acordă permisiuni Android: accesibilitatea și suprapunerea trebuie activate separat. Dacă abonamentul nu este activ, verificați dispozitivul, termenul și activarea în profil. Sincronizarea stării necesită conexiune cu serverul.")
            else -> t("Если системный экран специальных возможностей закрывается или отсутствует, обычная настройка службы невозможна. На магнитолах прошивка может иметь собственный экран разрешений. Откройте обходные способы и выберите инструкцию для устройства. После настройки вернитесь к проверке: только подключённая служба подтверждает, что чтение заказов работает.", "Dacă ecranul de accesibilitate lipsește sau se închide, configurarea normală nu este posibilă. Unitățile auto pot avea un ecran propriu de permisiuni. Deschideți metodele alternative, apoi verificați conectarea reală a serviciului.")
        }
    }
}
